#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd its [enddate [startdate] ] < its-analysis.R > script.out

# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by CVSAnalY2
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user
#  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
#      (in fact, first day after the period)
#  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
#
# # Authors :
#       Jesus Gonzalez Barahona <jgb@bitergia.com>
#       Alvaro del Castillo San Felix <acs@bitergia.com>
#

source("./its-lib.R")

options <- parse_options()

mychannel = connectDB(options)

enddatesplit <- strsplit(options$enddate,'-')
endyear <- enddatesplit[[1]][1]
endmonth <- enddatesplit[[1]][2]
enddate <- paste (c("'", options$enddate, "'"), collapse='')

startdatesplit <- strsplit(options$startdate,'-')
startyear <- startdatesplit[[1]][1]
startmonth <- startdatesplit[[1]][2]
startdate <- paste (c("'", options$startdate, "'"), collapse='')

closed_condition <- "(new_value='RESOLVED' OR new_value='CLOSED')"
if (!is.null(options$its)) {
	if (options$its == 'allura') closed_condition <- "new_value='CLOSED'"
	if (options$its == 'github') closed_condition <- "field='closed'"
}


closed_monthly <- evol_closed(closed_condition)
changed_monthly <- evol_changed()
open_monthly <- evol_opened()
repos_monthly <- evol_repositories();

issues_monthly <- merge (open_monthly, closed_monthly, all = TRUE)
issues_monthly <- merge (issues_monthly, changed_monthly, all = TRUE)
issues_monthly <- merge (issues_monthly, repos_monthly, all = TRUE)
issues_monthly[is.na(issues_monthly)] <- 0

issues_monthly <- completeZeroMonthly(issues_monthly)

createJSON (issues_monthly, "../data/json/its-evolutionary.json")

all_static_info <- static_info()
createJSON (all_static_info, "../data/json/its-static.json")

# Top closers
top_closers_data <- list()
top_closers_data[['closers.']]<-top_closers()
top_closers_data[['closers.last year']]<-top_closers(365)
top_closers_data[['closers.last month']]<-top_closers(31)

createJSON (top_closers_data, "../data/json/its-top.json")

# People List for working in unique identites
people_list <- people()
createJSON (people_list, "../data/json/its-people.json")

# Repositories
if (options$reports == 'repositories') {	
	repos  <- repos_name()
	repos <- repos$name
	createJSON(repos, "../data/json/its-repos.json")
	
	for (repo in repos) {
		repo_name = paste(c("'", repo, "'"), collapse='')
		repo_aux = paste(c("", repo, ""), collapse='')
		repo_file = gsub("/","_",repo)
		print (repo_name)
		
		# EVOLUTION INFO
		closed <- repo_evol_closed(repo_name, closed_condition)
		changed <- repo_evol_changed(repo_name)
		opened <- repo_evol_opened(repo_name)		
		agg_data = merge(closed, changed, all = TRUE)
		agg_data = merge(agg_data, opened, all = TRUE)	
		agg_data[is.na(agg_data)] <- 0				
		createJSON(agg_data, paste(c("../data/json/",repo_file,"-its-evolutionary.json"), collapse=''))
		
		# STATIC INFO
		static_info <- static_info_repo(repo_name)
		createJSON(static_info, paste(c("../data/json/",repo_file,"-its-static.json"), collapse=''))		
	}
}


# Disconnect from DB
dbDisconnect(con)

