#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd [enddate [startdate] ] < its-analysis.R > script.out

# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by CVSAnalY2
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user
#  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
#      (in fact, first day after the period)
#  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
#
# Note: this script works with bicho databases obtained from Bugzilla

# Get command line args, and produce variables for the script
args <- commandArgs(trailingOnly = TRUE)
print(args)

database <- args[1]
user <- args[2]
password <- args[3]

if (length(args) > 3) {
   enddate <- args[4]
} else {
   enddate <- "2100-01-01"
}
enddatesplit <- strsplit(enddate,'-')
endyear <- enddatesplit[[1]][1]
endmonth <- enddatesplit[[1]][2]
enddate <- paste (c("'", enddate, "'"), collapse='')

if (length(args) > 4) {
   startdate <- args[5]
} else {
   startdate <- "1900-01-01"
}
startdatesplit <- strsplit(startdate,'-')
startyear <- startdatesplit[[1]][1]
startmonth <- startdatesplit[[1]][2]
startdate <- paste (c("'", startdate, "'"), collapse='')

library(rjson)
#
# Create a JSON file with some R object
#
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}

library(RMySQL)
#
# Connect to the database and prepare...
#
mychannel <- dbConnect(MySQL(), user=user, password=password, host="localhost", db=database)
query <- function(...) dbGetQuery(mychannel, ...)

# To install RColorBrewer
# $sudo R
# > install.packages('RColorBrewer', dep = T)
# Exit R
library(RColorBrewer)

source("swscopio.R")

# Closed tickets: time ticket was open, first closed, time-to-first-close
q <- "SELECT issue_id, issue,
        submitted_on as time_open,
        time_closed,
    time_closed_last,
    TIMESTAMPDIFF (DAY, submitted_on, ch.time_closed) AS ttofix
      FROM issues, (
         SELECT
           issue_id,
           MIN(changed_on) AS time_closed,
           MAX(changed_on) as time_closed_last
         FROM changes
         WHERE (new_value='RESOLVED' OR new_value='CLOSED')
         GROUP BY issue_id) ch
      WHERE issues.id = ch.issue_id"
res_issues_closed <- query(q)


# Opened and openers
q <- paste ("SELECT year(submitted_on) * 12 + month(submitted_on) AS id,
               year(submitted_on) AS year,
               month(submitted_on) AS month,
	       DATE_FORMAT (submitted_on, '%b %Y') as date,
               count(submitted_by) AS open,
               count(distinct(submitted_by)) AS openers
             FROM issues
	     GROUP BY year,month
	     ORDER BY year,month")
open_monthly <- query(q)
# Reopened and reopeners
q <- paste ("SELECT year(changed_on) * 12 + month (changed_on) AS id,
               year(changed_on) as year,
               month(changed_on) as month,
               DATE_FORMAT (changed_on, '%b %Y') as date,
               count(issue_id) AS reopen,
               count(distinct(changed_by)) AS reopeners
             FROM changes
             WHERE new_value='REOPENED'
             GROUP BY year,month
         ORDER BY year,month")
reopened_monthly <- query(q)

# Closed and closers
q <- paste ("SELECT year(changed_on) * 12 + month (changed_on) AS id,
               year(changed_on) as year,
               month(changed_on) as month,
               DATE_FORMAT (changed_on, '%b %Y') as date,
               count(issue_id) AS closed,
               count(distinct(changed_by)) AS closers
             FROM changes
             WHERE new_value='CLOSED' 
             GROUP BY year,month
         ORDER BY year,month")
closed_monthly <- query(q)

# Changed and changers 
q <- paste ("SELECT year(changed_on) * 12 + month (changed_on) AS id,
               year(changed_on) as year,
               month(changed_on) as month,
           DATE_FORMAT (changed_on, '%b %Y') as date,
               count(changed_by) AS changed,
               count(distinct(changed_by)) AS changers
             FROM changes
             GROUP BY year,month
         ORDER BY year,month")
changed_monthly <- query(q)


issues_monthly <- merge (open_monthly, closed_monthly)
issues_monthly <- merge (issues_monthly, reopened_monthly)
issues_monthly <- merge (issues_monthly, changed_monthly)

createJSON (issues_monthly, "../data/json/its-milestone1.json")

# Disconnect from DB
dbDisconnect(con)
