# Copyright (C) 2012 Bitergia
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Authors :
#       Daniel Izquierdo Cortazar <dizquierdo@bitergia.com>
#       Alvaro del Castillo <acs@bitergia.com>




# This script tests the mileston1.R library found in common dir 

#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd < test.R > script.out

#
# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by CVSAnalY2
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user




# Get command line args, and produce variables for the script
args <- commandArgs(trailingOnly = TRUE)
print(args)

database <- args[1]
user <- args[2]
password <- args[3]


library(rjson)
#
# Create a JSON file with some R object
#
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}


#
# Library with queries
#
source("./milestone1.R")

#Commits per month
data_commits = evol_commits()

#Commits per month no Liferay
data_commits_noLiferay = evol_commits_noLiferay()


#Committers per month
data_committers = evol_committers()

# Authors per month
data_authors = evol_authors()

# Authors per month no Liferay
data_authors_noLiferay = evol_authors_noLiferay()

#Files per month
data_files = evol_files()

#Branches per month
data_branches = evol_branches()

#Repositories per month
data_repositories = evol_repositories()

# Lines added per month
data_lines_added = evol_lines_added()

# Lines removed per month
data_lines_removed = evol_lines_removed()


agg_data = merge(data_commits, data_commits_noLiferay)
agg_data = merge(agg_data, data_committers)
agg_data = merge(agg_data, data_authors)
agg_data = merge(agg_data, data_authors_noLiferay)
agg_data = merge(agg_data, data_files)
agg_data = merge(agg_data, data_branches)
agg_data = merge(agg_data, data_repositories)
agg_data = merge(agg_data, data_lines_added)
agg_data = merge(agg_data, data_lines_removed)

createJSON (agg_data, "../data/json/scm-milestone1.json")