#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd [enddate [startdate] ] < scm-analysis.R > script.out

#
# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by CVSAnalY2
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user
#  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
#      (in fact, first day after the period)
#  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
#

# Get command line args, and produce variables for the script
args <- commandArgs(trailingOnly = TRUE)
print(args)

database <- args[1]
user <- args[2]
password <- args[3]

if (length(args) > 3) {
   enddate <- args[4]
} else {
   enddate <- "2100-01-01"
}
enddatesplit <- strsplit(enddate,'-')
endyear <- enddatesplit[[1]][1]
endmonth <- enddatesplit[[1]][2]
enddate <- paste (c("'", enddate, "'"), collapse='')

if (length(args) > 4) {
   startdate <- args[5]
} else {
   startdate <- "1900-01-01"
}
startdatesplit <- strsplit(startdate,'-')
startyear <- startdatesplit[[1]][1]
startmonth <- startdatesplit[[1]][2]
startdate <- paste (c("'", startdate, "'"), collapse='')

#
# Build a time serie from a date frame, by month, starting the first month
#
createTimeSerie <- function (data, columns) {
   timeserie <- ts(data[columns],
      start=c(data$year[1],data$month[1]), frequency=12)
   return (timeserie)
}

#
# List of colors for plots
#
colors <- c("black", "green", "red", "blue", "orange", "brown")

#
# Plot several columns of a timeserie
#
#  data: data frame to plot
#  columns: names of the columns in data frame to plot
#  labels: strings to show as labels
#

plotTimeSerieN <- function (data, columns, filename, labels=columns) {
   pdffilename <- paste (c(filename, ".pdf"), collapse='')
   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')

   # Build label for Y axis
   label <- ""
   for (col in 1:length(columns)) {
      if (col != 1) {
         label <- paste (c(label, " / "), collapse='')
      }
      label = paste (c(label, labels[col], " (", colors[col] ,")"),
                     collapse='')
   }

   # Regular plot
   pdf(file=pdffilename, height=3.5, width=5)
   timeserie <- ts (data[columns[1]],
      start=c(data$year[1],data$month[1]), frequency=12)
   ts.plot (timeserie, col=colors[1], ylab=label)
   if (length (columns) > 1) {
      for (col in 2:length(columns)) {
         timeserie <- ts (data[columns[col]],
            start=c(data$year[1],data$month[1]), frequency=12)
         lines (timeserie, col=colors[col])
      }
   }
   dev.off()

   # Cummulative plot
   pdf(file=pdffilenamecum, height=3.5, width=5)
   timeserie <- ts (cumsum(data[columns[1]]),
      start=c(data$year[1],data$month[1]), frequency=12)
   ts.plot (timeserie, col=colors[1], ylab=label)
   if (length (columns) > 1) {
      for (col in 2:length(columns)) {
         timeserie <- ts (cumsum(data[columns[col]]),
            start=c(data$year[1],data$month[1]), frequency=12)
         lines (timeserie, col=colors[col])
      }
   }
   dev.off()
}


# Prepare a vector for using in moving average (for smoothing)
k = c(.5,1,1,1,.5)
k = k/sum(k)
#
# Smooth a time serie
#
# ts: time serie to smooth
#
smoothTimeSerie <- function (ts) {
   return (filter(ts, sides=2, k))
}

#
# Plot a column of a time serie, with a smoothed line over it,
#  a diffed graph of that same column, and a cummulative (cumsum)
#  graph of it
# 
# data: dataframe with the time serie (each row corresponds to a month)
#     it should have columns named year and month
# column: column to plot
#
plotTimeSerie <- function (data, column, filename, label=column) {
   pdffilename <- paste (c(filename, ".pdf"), collapse='')
   pdffilenamediff <- paste (c(filename, "-diff.pdf"), collapse='')
   pdffilenamecum <- paste (c(filename, "-cumsum.pdf"), collapse='')
   timeserie <- ts (data[column],
      start=c(data$year[1],data$month[1]), frequency=12)
   timeserie_smooth <- smoothTimeSerie (timeserie)
   timeseriecum <- ts (cumsum(data[column]),
      start=c(data$year[1],data$month[1]), frequency=12)
   # Plot the smoothed plot
   pdf(file=pdffilename, height=3.5, width=5)
   ts.plot (timeserie, col="green", ylab=label)
   lines (timeserie_smooth, col="black")
   dev.off()
   # Plot the diffed plot
   ylabel <- paste (c(label, " (diff)"), collapse='')
   pdf(file=pdffilenamediff, height=3.5, width=5)
   ts.plot (diff(timeserie), col="green", ylab=ylabel)
   dev.off()
   # Plot the cummulative plot
   ylabel <- paste (c(label, " (cummulative)"), collapse='')
   pdf(file=pdffilenamecum, height=3.5, width=5)
   ts.plot (timeseriecum, col="green", ylab=ylabel)
   dev.off()
}

#
# Plot probability density of some variables
#
plotDensityN <- function (data, filename, columns, labels=columns) {
   pdffilename <- paste (c(filename, ".pdf"), collapse='')

   # Build label for Y axis
   label <- ""
   for (col in 1:length(columns)) {
      if (col != 1) {
         label <- paste (c(label, " / "), collapse='')
      }
      label = paste (c(label, labels[col], " (", colors[col] ,")"),
                     collapse='')
   }

   # Now, let's plot
   pdf(file=pdffilename, height=3.5, width=5)
   plot(density(log10(data[[columns[1]]])), xlab="Log10 scale",
        col=colors[1], ylab=label, main="")
   if (length (columns) > 1) {
      for (col in 2:length(columns)) {
         lines(density(log10(data[[columns[col]]])), col=colors[col])
      }
   }
   dev.off()
}

library(rjson)
#
# Create a JSON file with some R object
#
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}

library(RMySQL)
#
# Connect to the database and prepare...
#
mychannel <- dbConnect(MySQL(), user=user, password=password, host="localhost", db=database)
query <- function(...) dbGetQuery(mychannel, ...)

#
# Basic time series (commits and committers per month, and all that)
#
#  id: ordinal of the month (year*12+month)
#  year, month: year, month
#  date: year month (such as "Feb 2003")
#  commits, committers: per month
#  ratio: commits/committers per month
#

q <- paste ("SELECT id as id,
       months.year as year,
       months.month as month,
       DATE_FORMAT (months.date, '%b %Y') as date,
       COALESCE(permonth.commits,0) as commits,
       COALESCE(permonth.committers,0) as committers,
       COALESCE(permonth.ratio,0) as ratio
     FROM months
     LEFT JOIN (
       SELECT year(date) as year, month(date) as month, date,
         count(id) as commits, 
    	 count(distinct(committer_id)) as committers,
	 count(id)/count(distinct(committer_id)) as ratio
       FROM scmlog
       GROUP BY year(date), month(date)
       ORDER BY year(date), month(date)) permonth
     ON (months.year = permonth.year AND months.month = permonth.month)
     WHERE months.date >= ", startdate, " AND months.date < ", enddate)

data_commits <- query(q)
#data_commits_ts <- createTimeSerie (data_commits,
#   c('id','year','month','commits','committers','ratio'))
#data_commits_tssmooth <- smoothTimeSerie (data_commits_ts)

#
# Plot with commits per month
#
plotTimeSerie (data_commits, "commits", "commits-month", "Commits")

#
# Plot with committers per month
#
plotTimeSerie (data_commits, "committers", "committers-month", "Committers")

#
# Plot with commits per committer (mean per month)
#
plotTimeSerie (data_commits, "ratio", "commits-committer-month", "Commits per committer")

#
# JSON file with an array of values for each of the columns:
#  month, date, commits, committers, ratio
#
createJSON (data_commits, "../data/json/commits-timeserie.json")

#
# Time series with lines added, removed, etc.
#
#  month: ordinal of the month (year*12+month)
#  date: year month (such as "Feb 2003")
#  commits: per month
#  added, removed: lines added or removed per month
#  ratio: lines changed (added + removed) per commit
#

q <- paste ("SELECT id as id,
       months.year as year,
       months.month as month,
       DATE_FORMAT (months.date, '%b %Y') as date,
       COALESCE(permonth.commits,0) as commits,
       COALESCE(permonth.added,0) as added,
       COALESCE(permonth.removed,0) as removed,
       COALESCE(permonth.ratio,0) as ratio
     FROM months
     LEFT JOIN (
       SELECT year(date) as year, month(date) as month, date,
         count(s.id) as commits,
	 sum(added) as added,
	 sum(removed) as removed,
	 (sum(added)+sum(removed))/count(s.id) as ratio
       FROM scmlog s, commits_lines c
       WHERE s.id = c.commit_id
       GROUP BY year(date), month(date)
       ORDER BY year(date), month(date)) permonth
     ON (months.year = permonth.year AND months.month = permonth.month)
     WHERE months.date >= ", startdate, " AND months.date < ", enddate)

data_lines <- query(q)

#
# Plot with lines added and removed per month
#
plotTimeSerieN (data_lines, c("added","removed"), "added-removed-month",
	        c("Lines added", "removed"))

#
# Plot with lines changed per commit per month
#
plotTimeSerie (data_lines, "ratio", "changed-commit-month",
	       "Lines changed per commit (mean per month)")

#
# JSON file with an array of values for each of the columns:
#  month, date, commits, added, removed, ratio
#
createJSON (data_lines, "lines-timeserie.json")

#
# Activity (commits, changes, lines added and removed, etc.)
# Only branch 1 (master) is considered
#

q <- paste ("SELECT id as id,
       months.year as year,
       months.month as month,
       DATE_FORMAT (months.date, '%b %Y') as date,
       COALESCE(permonth.commits,0) as commits,
       COALESCE(permonth.changes,0) as changes,
       COALESCE(permonth.committers,0) as committers,
       COALESCE(permonth.added,0) as added,
       COALESCE(permonth.removed,0) as removed,
       COALESCE(permonth.ratio,0) as ratio,
       COALESCE(permonth.changes_commit,0) as changes_commit,
       COALESCE(permonth.added_change,0) as added_change,
       COALESCE(permonth.removed_change,0) as removed_change
     FROM months
     LEFT JOIN (
       SELECT year(date) as year,
         month(date) as month, date,
         count(distinct(s.id)) as commits,
         count(s.id) as changes,
         count(distinct(s.committer_id)) as committers,
	 sum(added) as added,
	 sum(removed) as removed,
	 (sum(added)+sum(removed))/count(s.id) as ratio,
         count(s.id)/count(distinct(s.id)) as changes_commit,
         sum(added)/count(s.id) as added_change,
         sum(removed)/count(s.id) as removed_change
       FROM (
          SELECT DISTINCT(scmlog.id) as id,
             scmlog.committer_id as committer_id,
             scmlog.date as date
          FROM scmlog, actions
          WHERE scmlog.id = actions.commit_id AND branch_id=1 
          ) s, commits_files_lines c
       WHERE s.id = c.commit
       GROUP BY year(date), month(date)
       ORDER BY year(date), month(date)) permonth
     ON (months.year = permonth.year AND months.month = permonth.month)
     WHERE months.date >= ", startdate, " AND months.date < ", enddate)

data_lines_1 <- query(q)

#
# Plot commits, changes per month for branch 1
#
plotTimeSerie (data_lines_1, "commits", "1-commits-month",
	       "Commits (branch 1)")
plotTimeSerie (data_lines_1, "changes", "1-changes-month",
	       "Changes (branch 1)")
plotTimeSerie (data_lines_1, "committers", "1-committers-month",
	       "Committers (branch 1)")
plotTimeSerieN (data_lines_1, c("added","removed"), "1-added-removed-month",
	        c("Branch 1: Lines added", "removed"))
plotTimeSerie (data_lines_1, "ratio", "1-changed-commit-month",
	       "Lines changed per commit (mean per month)")
plotTimeSerie (data_lines_1, "changes_commit", "1-files-commit-month",
	       "Files changed per commit")
plotTimeSerieN (data_lines_1, c("added_change","removed_change"),
	        "1-added-removed-change-month",
	        c("Branch 1 (per change): Lines added", "removed"))
plotDensityN (data_lines_1, "1-density-added-removed",
	      c("added", "removed"), c("Lines/month added", "removed"))


#
# Now, let's look to the general distributions related to activity, looking for outliers
#
data <- query("SELECT s.id, sum(added) as added, sum(removed) as removed, count(s.id) as files
               FROM (
                 SELECT DISTINCT(scmlog.id) as id, scmlog.date
                 FROM scmlog, actions
                   WHERE scmlog.id = actions.commit_id AND branch_id=1 
               ) s, commits_files_lines c
               WHERE date >= '1991-01-01' AND date < '2012-01-01' AND
                 s.id = c.commit
               GROUP BY s.id
               ORDER BY date")
#plot (sort(data[,2]), log="xy", type="p")
pdf(file="commits-files-branch1.pdf", height=3.5, width=5)
plot (data[,4], xlab="Commit index", ylab="Files")
dev.off()
pdf(file="commits-density-branch1.pdf", height=3.5, width=5)
plot(density(log10(data[,4])), xlab="Logaritmic scale", col="black", ylab="Probability density")
lines(density(log10(data[,2])), col="red")
lines(density(log10(data[,3])), col="green")
dev.off()
#
# And now, let's remove outliers (commits with files > 500)
#
data <- query("SELECT *
               FROM
                 (SELECT s.id, sum(added) as added, sum(removed) as removed, count(s.id) as files
                  FROM (
                    SELECT DISTINCT(scmlog.id) as id, scmlog.date
                    FROM scmlog, actions
                    WHERE scmlog.id = actions.commit_id AND branch_id=1 
                  ) s, commits_files_lines c
                  WHERE date >= '1991-01-01' AND date < '2012-01-01' AND
                    s.id = c.commit
                  GROUP BY s.id
                  ORDER BY date
               ) commit_sizes
               WHERE files < 500")
pdf(file="commits-files-nooutliers-branch1.pdf", height=3.5, width=5)
plot (data[,4], xlab="Commit index", ylab="Files")
dev.off()

#
# Metrics, including LOC, SLOC and number of files
# Only branch 1 (master) is considered
#
q <- paste ("SELECT id as id,
       months.year as year,
       months.month as month,
       DATE_FORMAT (months.date, '%b %Y') as date,
       COALESCE(permonth.loc,0) as loc,
       COALESCE(permonth.sloc,0) as sloc,
       COALESCE(permonth.files,0) as files,
       COALESCE(permonth.loc_files,0) as loc_files,
       COALESCE(permonth.sloc_files,0) as sloc_files
     FROM months
     LEFT JOIN (
       SELECT year(date) as year,
         month(date) as month,
         date,
	 loc, sloc, files,
	 loc/files as loc_files,
	 sloc/files as sloc_files
       FROM metrics_evo
       WHERE branch_id = 1
       ORDER BY date) permonth
     ON (months.year = permonth.year AND months.month = permonth.month)
     WHERE months.date >= ", startdate, " AND months.date < ", enddate)

data_size <- query(q)

#
# Plot number of files, loc, sloc, loc/files, sloc/files for each month
#
plotTimeSerieN (data_size, c("loc", "sloc"), "1-loc-sloc-month",
	        c("Branch 1: LOC", "SLOC"))
plotTimeSerie (data_size, "files", "1-files-month",
	       "Branch 1: Files")
plotTimeSerieN (data_size, c("loc_files", "sloc_files"),
	        "1-loc-sloc-files-month",
	        c("Branch 1 (per file): LOC", "SLOC"))
