# Copyright (C) 2012 Bitergia
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Authors :
#       Daniel Izquierdo Cortazar <dizquierdo@bitergia.com>
#       Alvaro del Castillo San Felix <acs@bitergia.com>




# This script tests the mileston0.R library found in common dir 

#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd < test.R > script.out

#
# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by CVSAnalY2
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user




# Get command line args, and produce variables for the script
args <- commandArgs(trailingOnly = TRUE)
print(args)

database <- args[1]
user <- args[2]
password <- args[3]


library(rjson)
#
# Create a JSON file with some R object
#
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}


#
# Library with queries
#
source("./webkit.R")


#Commits per month
data_rev_commits = evol_rev_commits()

#People per month
data_authors_rev = evol_authors_rev()
#data_reviewers = evol_reviewers()

#companies per month
data_companies_rev = companies_evolution_rev()
#data_companies_notrev = companies_evolution_not_rev()

#Files per month
data_files_rev = evol_files_rev()


# Fixed data
info_data = evol_info_data_rev()

# Top authors
top_authors_data <- top_authors_rev()
top_authors_data_2006 <- top_authors_rev_year(2006)
top_authors_data_2009 <- top_authors_rev_year(2009)
top_authors_data_2012 <- top_authors_rev_year(2012)


agg_data = merge(data_rev_commits, data_authors_rev, all = TRUE)
agg_data = merge(agg_data, data_companies_rev, all = TRUE)
agg_data = merge(agg_data, data_files_rev, all = TRUE)
agg_data[is.na(agg_data)] <- 0

createJSON (agg_data, "../data/json/scm-evolutionary-info.json")
createJSON (info_data, "../data/json/scm-static-info.json")
createJSON (top_authors_data, "../data/json/scm-top-authors_rev.json")
createJSON (top_authors_data_2006, "../data/json/scm-top-authors_rev_2006.json")
createJSON (top_authors_data_2009, "../data/json/scm-top-authors_rev_2009.json")
createJSON (top_authors_data_2012, "../data/json/scm-top-authors_rev_2012.json")

#Companies

companies  <- companies_name()
companies <- companies$name
createJSON(companies, "../data/json/companies.json")

for (company in companies){
   company_name = paste(c("'", company, "'"), collapse='')
   company_aux = paste(c("", company, ""), collapse='')
   print (company_name)

   print ("commits") 
   commits_rev <- company_rev_commits(company_name)
   print ("lines")
   lines_rev <-company_lines_rev(company_name)
   print ("files")
   files_rev <- company_rev_files(company_name)
   print ("people")
   reviewers <- company_reviewers(company_name)
   authors_rev <- company_authors_rev(company_name)
  

   agg_data = merge(commits_rev, lines_rev, all = TRUE)
   agg_data = merge(agg_data, files_rev, all = TRUE)
   agg_data = merge(agg_data, reviewers, all = TRUE)
   agg_data = merge(agg_data, authors_rev, all = TRUE)

   createJSON(agg_data, paste(c("../data/json/",company_aux,"-scm-evolutionary-info.json"), collapse=''))

   print ("static info")
   static_info <- evol_info_data_company_rev(company_name)
   createJSON(static_info, paste(c("../data/json/",company_aux,"-scm-static-info.json"), collapse=''))

   print ("top authors")
   top_authors <- company_top_authors(company_name)
   createJSON(top_authors, paste(c("../data/json/",company_aux,"-scm-top-authors.json"), collapse=''))
   top_authors_rev <- company_top_authors_rev(company_name)
   createJSON(top_authors_rev, paste(c("../data/json/",company_aux,"-scm-top-authors_rev.json"), collapse=''))
   top_reviewers <- company_top_reviewers(company_name)
   createJSON(top_reviewers, paste(c("../data/json/",company_aux,"-scm-top-reviewers.json"), collapse=''))
   top_authors_rev_2006 <- company_top_authors_year_rev(company_name, 2006) 
   createJSON(top_authors_rev_2006, paste(c("../data/json/",company_aux,"-scm-top-authors_rev_2006.json"), collapse=''))
   top_authors_rev_2009 <- company_top_authors_year_rev(company_name, 2009)
   createJSON(top_authors_rev_2009, paste(c("../data/json/",company_aux,"-scm-top-authors_rev_2009.json"), collapse=''))
   top_authors_rev_2012 <- company_top_authors_year_rev(company_name, 2012)
   createJSON(top_authors_rev_2012, paste(c("../data/json/",company_aux,"-scm-top-authors_rev_2012.json"), collapse=''))



}
