#
# Usage:
#  R --no-restore --no-save --args dbschema user passwd [enddate [startdate] ] < mls-analysis.R > script.out

# Get arguments from the command line
#
#  - dbschema: MySQL database schema to use, generated by MLStats
#  - user: MySQL user with permissions to access the schema
#  - passwd: password corresponding to user
#  - enddate: final date of the period to analyze. Format: YYYY-MM-DD
#      (in fact, first day after the period)
#  - startdate: starting date of the period to analyze. Format: YYYY-MM-DD
#
# # Authors :
#       Jesus Gonzalez Barahona <jgb@bitergia.com>
#       Alvaro del Castillo San Felix <acs@bitergia.com>

# Note: this script works with MailingListStats tool
completeZeroMonthly <- function (data) {

  firstmonth = as.integer(data$id[1])
  lastmonth = as.integer(data$id[nrow(data)])
  months = data.frame('id'=c(firstmonth:lastmonth))
  completedata <- merge (data, months, all=TRUE)
  completedata[is.na(completedata)] <- 0
  return (completedata)
}


# Get command line args, and produce variables for the script
args <- commandArgs(trailingOnly = TRUE)
print(args)

database <- args[1]
user <- args[2]
password <- args[3]

if (length(args) > 3) {
   enddate <- args[4]
} else {
   enddate <- "2100-01-01"
}
enddatesplit <- strsplit(enddate,'-')
endyear <- enddatesplit[[1]][1]
endmonth <- enddatesplit[[1]][2]
enddate <- paste (c("'", enddate, "'"), collapse='')

if (length(args) > 4) {
   startdate <- args[5]
} else {
   startdate <- "1900-01-01"
}
startdatesplit <- strsplit(startdate,'-')
startyear <- startdatesplit[[1]][1]
startmonth <- startdatesplit[[1]][2]
startdate <- paste (c("'", startdate, "'"), collapse='')

library(rjson)
#
# Create a JSON file with some R object
#
createJSON <- function (data, filename) {
   sink(filename)
   cat(toJSON(data))
   sink()
}

library(RMySQL)
#
# Connect to the database and prepare...
#
mychannel <- dbConnect(MySQL(), user=user, password=password, host="localhost", db=database)
query <- function(...) dbGetQuery(mychannel, ...)

# To install RColorBrewer
# $sudo R
# > install.packages('RColorBrewer', dep = T)
# Exit R
library(RColorBrewer)

source("swscopio.R")

analList <- function (listname) {

    field = "mailing_list"
    listname_file = gsub("/","_",listname)

    if(length(i <- grep("http",listname))) {
        field = "mailing_list_url"
        cat(listname, " is a URL\n")
    }


	# Messages sent	
	q <- paste("SELECT year(first_date) * 12 + month(first_date) AS id,
	               year(first_date) AS year,
	               month(first_date) AS month,
		           DATE_FORMAT (first_date, '%b %Y') as date,
	               count(message_ID) AS sent
	             FROM messages WHERE ",field,"='",listname,"'
		         GROUP BY year,month
		         ORDER BY year,month",sep = '') 
	
	sent_monthly <- query(q)
	
	print (sent_monthly)
	
	# All subjects
	
	q <- paste ("SELECT year(first_date) * 12 + month(first_date) AS id,
	               year(first_date) AS year,
	               month(first_date) AS month,
	               DATE_FORMAT (first_date, '%b %Y') as date,
	               subject
	             FROM messages  WHERE ",field,"='",listname,"'
	             ORDER BY year,month", sep = '')
	subjects_monthly <- query(q)
	
	
	# Senders
	q <- paste ("SELECT year(first_date) * 12 + month(first_date) AS id,
	               year(first_date) AS year,
	               month(first_date) AS month,
	               DATE_FORMAT (first_date, '%b %Y') as date,
	               count(distinct(email_address)) AS senders
	             FROM messages
	             JOIN messages_people on (messages_people.message_id = messages.message_ID)
	             WHERE type_of_recipient='From' AND ",field,"='",listname,"'
	             GROUP BY year,month
	             ORDER BY year,month", sep = '')
	senders_monthly <- query(q)
	
	# All people monthly
	q <- paste ("SELECT year(first_date) * 12 + month(first_date) AS id,
	               year(first_date) AS year,
	               month(first_date) AS month,
	               DATE_FORMAT (first_date, '%b %Y') as date,
	               email_address
	             FROM messages
	             JOIN messages_people on (messages_people.message_id = messages.message_ID)
	             WHERE type_of_recipient='From' AND ",field,"='",listname,"'
	             ORDER BY year,month", sep = '')
	emails_monthly <- query(q)
	
	mls_monthly <- completeZeroMonthly (merge (sent_monthly, senders_monthly, all = TRUE))
    mls_monthly[is.na(mls_monthly)] <- 0
	createJSON (mls_monthly, paste("../data/json/mls-",listname_file,"-milestone0.json",sep=''))
	# createJSON (subjects_monthly, paste("../data/json/mls-",listname,"-subjects-milestone0.json",sep=''))
	createJSON (emails_monthly, paste("../data/json/mls-",listname_file,"-emails-milestone0.json",sep=''))

    ## Get some general stats from the database
    ##
    q <- paste ("SELECT count(*) as messages,
             DATE_FORMAT (min(first_date), '%Y-%m-%d') as first_date,
             DATE_FORMAT (max(first_date), '%Y-%m-%d') as last_date,
             COUNT(DISTINCT(email_address)) as people
             FROM messages 
	         JOIN messages_people on (messages_people.message_id = messages.message_ID)
             WHERE ",field,"='",listname,"'",sep='')
    data <- query(q)
    createJSON (data, paste("../data/json/mls-",listname_file,"-info-milestone0.json",sep=''))
}


# Mailing lists
q <- paste ("select distinct(mailing_list) from messages")
mailing_lists <- query(q)

if (is.na(mailing_lists$mailing_list)) {
    print ("URL Mailing List")
    q <- paste ("select distinct(mailing_list_url) from messages")
    mailing_lists <- query(q)
    mailing_lists_files <- query(q) 
    mailing_lists_files$mailing_list = gsub("/","_",mailing_lists$mailing_list)
    # print (mailing_lists)
    createJSON (mailing_lists_files, "../data/json/mls-lists-milestone0.json")
} else {
    print (mailing_lists)
    createJSON (mailing_lists, "../data/json/mls-lists-milestone0.json")
}

# Aggregated data
q <- paste ("SELECT count(*) as messages,
    DATE_FORMAT (min(first_date), '%Y-%m-%d') as first_date,
    DATE_FORMAT (max(first_date), '%Y-%m-%d') as last_date
    FROM messages")
num_msg <- query(q)
q <- paste ("SELECT count(*) as people from people")
num_ppl <- query(q)

agg_data = merge(num_msg,num_ppl)

createJSON (agg_data, paste("../data/json/mls-info-milestone0.json",sep=''))


for (mlist in mailing_lists$mailing_list) {
    analList(mlist)
}

# Disconnect from DB
dbDisconnect(con)
